#!/usr/bin/env bash
set -e
if [ $# -lt 1 ]
then
	echo "Usage: $(basename "$0") [SECRET_HASH]"
	exit 1
fi

grep "$1" node_*_00?/run-"$(cat run_number.txt)".log -h | grep '^{' | jq 'select(.raiden_events) | {timestamp, node, re: .raiden_events[]._type}' -c > re.jsonl
grep "$1" node_*_00?/run-"$(cat run_number.txt)".log -h | grep '^{' | jq 'select(.state_changes) | {timestamp, node, sc: .state_changes[]._type}' -c > sc.jsonl
cat {re,sc}.jsonl | sort | jq . -c
